# Config for how content is created, modified and previewed using the Netlify CMS GUI.
# ====================================================================================

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow # Ensures content goes through workflow first, ("Drafts" --> "In Review" --> "Ready"), before being published
media_folder: "src/assets/images/uploads" # Media files will be stored in the repo under src/assets/images/uploads
public_folder: "/assets/images/uploads" # The src attribute for uploaded media will begin with /assets/images/uploads
site_url: "https://bostontparty.co.za"
display_url: "https://bostontparty.co.za"
logo_url: "https://bostontparty.co.za/assets/images/common/logo.png"

collections:
  # 'Pages'
  - label: "Pages"
    name: "pages"
    files:
      - label: "Accommodation page"
        name: "accommodation"
        file: "src/_content/pages/accommodation.md"
        preview_path: "accommodation"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Lead", name: "lead", widget: "string" }
          - {
              label: "Updated Date",
              name: "updated",
              widget: "datetime",
              picker_utc: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
